[loggers]
keys=root,lib,game

[handlers]
keys=basicConsoleHandler,gameConsoleHandler

[formatters]
keys=basicFormatter,gameFormatter


[logger_root]
level=DEBUG
handlers=

[logger_lib]
level=DEBUG
handlers=basicConsoleHandler
qualname=jloxgame
propagate=0

[logger_game]
level=DEBUG
handlers=gameConsoleHandler
qualname=jloxgame.game
propagate=0


[handler_basicConsoleHandler]
class=StreamHandler
level=DEBUG
formatter=basicFormatter
args=(sys.stdout,)

[handler_gameConsoleHandler]
class=StreamHandler
level=INFO
formatter=gameFormatter
args=(sys.stdout,)


[formatter_basicFormatter]
format=%(asctime)s [jloxgame | %(levelname)s] %(message)s

[formatter_gameFormatter]
format=%(asctime)s [%(gameId)s | %(levelname)s] %(message)s