[loggers]
keys=root,lib,event,bot

[handlers]
keys=basicConsoleHandler,eventConsoleHandler,botConsoleHandler

[formatters]
keys=basicFormatter,eventFormatter,botFormatter


[logger_root]
level=DEBUG
handlers=

[logger_lib]
level=DEBUG
handlers=basicConsoleHandler
qualname=jloxgame
propagate=0

[logger_bot]
level=INFO
handlers=botConsoleHandler
qualname=jloxgame.bot

[logger_event]
level=DEBUG
handlers=eventConsoleHandler
qualname=jloxevent
propagate=0


[handler_basicConsoleHandler]
class=StreamHandler
level=DEBUG
formatter=basicFormatter
args=(sys.stdout,)

[handler_botConsoleHandler]
class=StreamHandler
level=INFO
formatter=botFormatter
args=(sys.stdout,)

[handler_eventConsoleHandler]
class=StreamHandler
level=DEBUG
formatter=eventFormatter
args=(sys.stdout,)


[formatter_basicFormatter]
format=%(asctime)s [jloxgame | %(levelname)s] %(message)s

[formatter_botFormatter]
format=%(asctime)s [%(gameId)s | %(levelname)s] %(message)s

[formatter_eventFormatter]
format=%(asctime)s [%(gameId)s | %(eventType)s | %(levelname)s] %(message)s